apiVersion: v1
kind: Secret
metadata:
  name: django-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/zhyvka89/devOps.git
  type: git
